version: '3.9'
services:
  postgres:
    image: bitnami/postgresql:16
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=freelancer_management_db
    volumes:
      - freelancer_pg_data:/bitnami/postgresql
volumes:
  freelancer_pg_data:
